if argument0=0 return "Enram BR-417"
if argument0=1 return "Bartoli FR-12 Enforcer" // SPAS-12
if argument0=2 return "3-iron"
if argument0=3 return "Gas conduit"
if argument0=4 return "Steel bat"
if argument0=5 return "Chef's knife"
if argument0=6 return "Sedgewick 707" // Double-barrel
if argument0=7 return "Enram 5.7 Whisper" // Suppressed handgun
if argument0=8 return "Katana"
if argument0=9 return "Autsi PM-9" // Uzi
if argument0=10 return "Elmwood .38 Absolver" // Magnum revolver
if argument0=11 return "Z&M Sz.-336" // Skorpion
if argument0=12 return "SB Macht 37" // MP5
if argument0=13 return "Pool cue"
if argument0=14 return "AM MRS-4R" // M16
if argument0=15 return "Fire axe"
if argument0=16 return "Police tonfa"
if argument0=17 return "Crowbar"
if argument0=18 return "Machete"
if argument0=19 return "Sledgehammer"
if argument0=20 return "Trophy"
if argument0=21 return "H&H 18V cordless drill"
if argument0=22 return "Frying pan"
if argument0=23 return "Steel pot (boiling water)"
if argument0=24 return "Steel pot (empty)"
if argument0=25 return "Enram SMG-11" // Suppressed Uzi
if argument0=26 return "SVG-76" // Kalashnikov
if argument0=27 return "SB Zenith CA-40" // Handgun
if argument0=28 return "Isando MIL-50" // Flamethrower
if argument0=29 return "Bronson M310" // Intervention
if argument0=30 return "Enram TAC-12" // Suppressed shotgun
if argument0=31 return "H&H 455 chainsaw"
if argument0=32 return "AM BLK-300 Tactical" // Honey badger
if argument0=33 return "H&H DT240K precision brad nailer" // Nailgun
if argument0=34 return "Bicycle chain"
if argument0=35 return "Meat cleaver"
if argument0=36 return "H&H Type 10 signal pistol" // Flare gun
if argument0=37 return "Skateboard"
if argument0=38 return "RE.44LIZER" // Realizer
if argument0=39 return "Mannequin arm"
if argument0=40 return "Statue bust"
if argument0=41 return "Bronson M1928" // Thompson
if argument0=42 return "Aries Mk48 Vindicator" // LMG
if argument0=43 return "SB Geist" // Crossbow
if argument0=44 return "Electric guitar"
if argument0=45 return "Mayweather .30" // M1 Garand
if argument0=46 return "Great scythe" 
if argument0=47 return "Aries ATSG-12 Annihilator" // AA-12
if argument0=48 return "" // unlisted
if argument0=49 return "SB Sieger 300" // WA2000 
if argument0=50 return "Rip hammer"
if argument0=51 return "Pipe wrench"
if argument0=52 return "Aries D50 Punisher" // Desert Eagle
if argument0=53 return "H&H lightweight magnesium#cordless circular saw"
if argument0=54 return "Enram HV-12" // KSG
if argument0=55 return "Enram TAC-SMG"
if argument0=56 return "Hand hatchet"
if argument0=57 return "Bartoli Auto 9" // AJM-9
if argument0=58 return "Prototype injection-based MF scatter rifle" // Multiplas
if argument0=59 return "Hyper-velocity energy modulation cannon, v17" // Disruptor rifle
if argument0=60 return "Isando CL-40" // M79
if argument0=61 return "Isando RGL-220" // MGL-140
if argument0=62 return "Autsi M712" // Mauser
if argument0=63 return "Isando RPG-6G3" // RPG-7
if argument0=64 return "The Patriot" // The Patriot
if argument0=65 return "Medicinal water pipe" 
if argument0=66 return "Battle axe"
if argument0=67 return "Shovel"
if argument0=68 return "Elmwood 1889 Peacemaker" // Single Action Army
if argument0=69 return "Elmwood 1878 Lupara" // Sawed-off shotgun
if argument0=70 return "Liquor bottle"
if argument0=71 return "Bartoli Model 37 Stakeout" // Ithaca 37
if argument0=72 return "Hysteria"
if argument0=73 return "Recurve bow" // Bow
if argument0=74 return "Brick"
if argument0=75 return "Heavy steam pipe"
if argument0=76 return "Jaeger SAF-9 SD" // FAMAE
if argument0=77 return "STG 58 Elite" // FAL
if argument0=78 return "Elmwood 1925 Exterminatore" // Model 1887
if argument0=79 return "Knight's glaive"
if argument0=80 return "Leviathan"
if argument0=81 return "Executioner's greatsword"
if argument0=82 return "Morningstar mace"
if argument0=83 return "Fire extinguisher"
if argument0=84 return "Screwdriver"
if argument0=85 return " " // Blank
if argument0=86 return "Briefcase"
if argument0=87 return "Electroshock stun baton"
if argument0=88 return "Some kind of large fish"
if argument0=89 return "Pitchfork"
if argument0=90 return "Street sign"
if argument0=91 return "Heavy-duty hedge shears"
if argument0=92 return "Acid soaker" 
if argument0=93 return "A pair of sewing scissors"
if argument0=94 return "KAGURA High Tides Super Soaker"
if argument0=95 return "KAGURA Mega Burst Blaster"
if argument0=96 return "KAGURA Big Splash Balloon Launcher"
if argument0=97 return "KAGURA Jet Stream Longshot"
if argument0=98 return "KAGURA Ultra Spray Shower Cannon"
return 0
