if argument0=sprPAttackSkateboard return true
if argument0=sprPAttackHammer return true
if argument0=sprPAttackBrick return true
if argument0=sprPAttackWrench return true
if argument0=sprPAttackScrewdriver return true
if argument0=sprPAttackBottle return true
if argument0=sprPAttackBottleBroken return true
if argument0=sprPAttackAxe return true
if argument0=sprPAttackKnife return true
if argument0=sprPAttackKnifeSlash1 return true
if argument0=sprPAttackKnifeSlash2 return true
if argument0=sprPAttackKnifeStab return true
if argument0=sprPAttackKitchenKnife return true
if argument0=sprPAttackKnifePistol return true
if argument0=sprPAttackTaser return true
if argument0=sprPAttackPipe return true
if argument0=sprPAttackBat return true
if argument0=sprPAttackBag return true
if argument0=sprPAttackClub return true
if argument0=sprPAttackGuitar return true
if argument0=sprPAttackPool return true
if argument0=sprPAttackPoolBroke return true
if argument0=sprPAttackPan return true
if argument0=sprPAttackPot return true
if argument0=sprPAttackBoilingPot return true
if argument0=sprPAttackChainsaw return true
if argument0=sprPAttackHalberdH return true
if argument0=sprPAttackHalberdV return true
if argument0=sprPAttackLeviathan return true
if argument0=sprPAttackKatanaH1 return true
if argument0=sprPAttackKatanaH2 return true
if argument0=sprPAttackKatanaV return true
if argument0=sprPAttackKatanaThrust return true
if argument0=sprPAttackMachete return true
if argument0=sprPAttackLongSword1 or argument0=sprPAttackLongSword2 return true
if argument0=sprPAttackSledgeHammer return true
if argument0=sprPAttackCrowbar return true
if argument0=sprPAttackDrill return true
if argument0=sprPAttackChain return true
if argument0=sprPAttackBong return true
/*if argument0=sprPAttackScythe return true
if argument0=sprPAttackFish return true
if argument0=sprPAttackSign return true
if argument0=sprPAttackPitchfork return true
if argument0=sprPAttackHatchet return true*/
if argument0=sprPAttackCircularSaw return true
if argument0=sprPAttackCleaver return true
if argument0 = thomasStrikeL1
or argument0 = thomasStrikeL2
or argument0 = thomasStrikeL3
or argument0 = thomasStrikeL4
or argument0 = thomasStrikeR1
or argument0 = thomasStrikeR2
or argument0 = thomasStrikeR3
or argument0 = thomasStrikeR4 return true
if argument0 = simonePistolWhip return true
//if argument0 = pierretteAttackBaton1
//or argument0 = pierretteAttackBaton2 return true
if argument0 = pierretteBashShield return true
if argument0 = sprPAttackPunch 
or argument0 = sprPAttackBag 
or argument0 = sprPAttackDrill 
or argument0 = sprPAttackUnarmed1
or argument0 = sprPAttackUnarmed2 return true
if argument0 = sprPAttackDrill return true
if argument0=sprPAttackBust return true
if argument0=sprPAttackArm return true
if argument0=sprPAttackShovel return true

return false
